- class_object: langchain.document_loaders.AirbyteJSONLoader
- class_object: langchain.document_loaders.CoNLLULoader
- class_object: langchain.document_loaders.CSVLoader
- class_object: langchain.document_loaders.UnstructuredEmailLoader
- class_object: langchain.document_loaders.EverNoteLoader
- class_object: langchain.document_loaders.FacebookChatLoader
- class_object: langchain.document_loaders.GutenbergLoader
- class_object: langchain.document_loaders.BSHTMLLoader
- class_object: langchain.document_loaders.UnstructuredHTMLLoader
#  UnstructuredImageLoader # Issue with Python 3.11 (https://github.com/Unstructured-IO/unstructured-inference/issues/83)
- class_object: langchain.document_loaders.UnstructuredMarkdownLoader
- class_object: langchain.document_loaders.PyPDFLoader
- class_object: langchain.document_loaders.UnstructuredPowerPointLoader
- class_object: langchain.document_loaders.SRTLoader
- class_object: langchain.document_loaders.TelegramChatLoader
- class_object: langchain.document_loaders.TextLoader
- class_object: langchain.document_loaders.UnstructuredWordDocumentLoader
- class_object: langchain.document_loaders.WebBaseLoader
- class_object: langchain.document_loaders.AZLyricsLoader
- class_object: langchain.document_loaders.CollegeConfidentialLoader
- class_object: langchain.document_loaders.HNLoader
- class_object: langchain.document_loaders.IFixitLoader
- class_object: langchain.document_loaders.IMSDbLoader
- class_object: langchain.document_loaders.GitbookLoader
- class_object: langchain.document_loaders.ReadTheDocsLoader
- class_object: langchain.document_loaders.SlackDirectoryLoader
- class_object: langchain.document_loaders.NotionDirectoryLoader
- class_object: langchain.document_loaders.DirectoryLoader
- class_object: langchain.document_loaders.GitLoader
