- class_object: langchain.llms.OpenAI
  documentation: https://python.langchain.com/docs/modules/model_io/models/llms/integrations/openai
- class_object: langchain.llms.LlamaCpp
  documentation: https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp
- class_object: langchain.llms.CTransformers
  documentation: https://python.langchain.com/docs/modules/model_io/models/llms/integrations/ctransformers
- class_object: langchain.llms.Cohere
  documentation: https://python.langchain.com/docs/modules/model_io/models/llms/integrations/cohere
- class_object: langchain.llms.Anthropic
  documentation: ''
- class_object: langchain.llms.HuggingFaceHub
  documentation: https://python.langchain.com/docs/modules/model_io/models/llms/integrations/huggingface_hub
- class_object: langchain.chat_models.ChatAnthropic
  documentation: https://python.langchain.com/docs/modules/model_io/models/chat/integrations/anthropic
- class_object: langchain.chat_models.ChatOpenAI
  documentation: https://python.langchain.com/docs/modules/model_io/models/chat/integrations/openai
