- class_object: langchain.agents.load_tools.Search
  documentation: ''
- class_object: langchain.tools.PAL-MATH
  documentation: ''
- class_object: langchain.tools.Calculator
  documentation: ''
- class_object: langchain.tools.Serper Search
  documentation: ''
- class_object: langchain.tools.Tool
  documentation: ''
- class_object: langchain.tools.PythonFunctionTool
  documentation: ''
- class_object: langchain.tools.PythonFunction
  documentation: ''
- class_object: langchain.tools.JsonSpec
  documentation: ''
- class_object: langchain.tools.News API
  documentation: ''
- class_object: langchain.tools.TMDB API
  documentation: ''
- class_object: langchain.tools.Podcast API
  documentation: ''
- class_object: langchain.tools.QuerySQLDataBaseTool
  documentation: ''
- class_object: langchain.tools.InfoSQLDatabaseTool
  documentation: ''
- class_object: langchain.tools.ListSQLDatabaseTool
  documentation: ''
- class_object: langchain.tools.BingSearchRun
  documentation: ''
- class_object: langchain.tools.GoogleSearchRun
  documentation: ''
- class_object: langchain.tools.GoogleSearchResults
  documentation: ''
- class_object: langchain.tools.GoogleSerperRun
  documentation: ''
- class_object: langchain.tools.JsonListKeysTool
  documentation: ''
- class_object: langchain.tools.JsonGetValueTool
  documentation: ''
- class_object: langchain.tools.PythonREPLTool
  documentation: ''
- class_object: langchain.tools.PythonAstREPLTool
  documentation: ''
- class_object: langchain.tools.RequestsGetTool
  documentation: ''
- class_object: langchain.tools.RequestsPostTool
  documentation: ''
- class_object: langchain.tools.RequestsPatchTool
  documentation: ''
- class_object: langchain.tools.RequestsPutTool
  documentation: ''
- class_object: langchain.tools.RequestsDeleteTool
  documentation: ''
- class_object: langchain.tools.WikipediaQueryRun
  documentation: ''
- class_object: langchain.tools.WolframAlphaQueryRun
  documentation: ''
